### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by CosmicHorrorDev** [crabique/Nord-plist#1]
Hi, thanks for the great looking theme! I have a project that winds up embedding this as one of the default themes and was wondering if the license could be clarified. I see that there's an outdated looking MIT header in the theme itself

https://github.com/crabique/Nord-plist/blob/0d655b23d6b300e691676d9b90a68d92b267f7ec/Nord.tmTheme#L1-L12

Is that enough to say that this repo is available under the MIT license? Adding a full license file would be nice to have as well

**Comment by crabique** [comment]
Hi there! Unfortunately, I'm unable offer any legal advice regarding the licensing terms and conditions. To be completely on the safe side, I would suggest using the assets directly from the [original repo @ 0f1657d](https://github.com/nordtheme/sublime-text/tree/0f1657daa79797ad9cd1e3caa92e2cb277571b0b), back when they were still using the XML format.

The reason I created this repo was the fear that the original repository might be deleted/commit history rewritten, but it turns out it will likely stay there indefinitely.

That said, I copied the original license file just in case too.

**Comment by CosmicHorrorDev** [comment]
The MIT license works perfectly fine for me!

(I am not a lawyer, but) The MIT license is very permissive and is compatible with itself, so you should be fine releasing this repo under the same license since it keeps the original attribution
